"""add codemind repository and code file models

Revision ID: 811a53cca653
Revises: fb3d7cd97083
Create Date: 2026-09-27 18:11:09.772614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811a53cca653'
down_revision: Union[str, Sequence[str], None] = 'fb3d7cd97083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('remote_url', sa.String(length=1000), nullable=True),
    sa.Column('local_path', sa.String(length=1000), nullable=True),
    sa.Column('default_branch', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("provider IN ('local', 'github')", name='check_code_repository_provider'),
    sa.CheckConstraint("status IN ('active', 'archived')", name='check_code_repository_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_id', 'name', name='uq_code_repository_project_name')
    )
    op.create_index(op.f('ix_code_repositories_id'), 'code_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_code_repositories_organization_id'), 'code_repositories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_code_repositories_project_id'), 'code_repositories', ['project_id'], unique=False)
    op.create_table('code_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1500), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'deleted')", name='check_code_file_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['code_repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'file_path', name='uq_code_file_repository_path')
    )
    op.create_index(op.f('ix_code_files_id'), 'code_files', ['id'], unique=False)
    op.create_index(op.f('ix_code_files_organization_id'), 'code_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_code_files_project_id'), 'code_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_code_files_repository_id'), 'code_files', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_files_repository_id'), table_name='code_files')
    op.drop_index(op.f('ix_code_files_project_id'), table_name='code_files')
    op.drop_index(op.f('ix_code_files_organization_id'), table_name='code_files')
    op.drop_index(op.f('ix_code_files_id'), table_name='code_files')
    op.drop_table('code_files')
    op.drop_index(op.f('ix_code_repositories_project_id'), table_name='code_repositories')
    op.drop_index(op.f('ix_code_repositories_organization_id'), table_name='code_repositories')
    op.drop_index(op.f('ix_code_repositories_id'), table_name='code_repositories')
    op.drop_table('code_repositories')
    # ### end Alembic commands ###
