"""create data source files table

Revision ID: f9e4c1cf9d82
Revises: 89e23e6d2a57
Create Date: 2026-09-17 16:44:08.955660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e4c1cf9d82'
down_revision: Union[str, Sequence[str], None] = '89e23e6d2a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'deleted')", name='check_data_source_file_status'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'file_path', name='uq_data_source_file')
    )
    op.create_index(op.f('ix_data_source_files_data_source_id'), 'data_source_files', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_source_files_id'), 'data_source_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_source_files_id'), table_name='data_source_files')
    op.drop_index(op.f('ix_data_source_files_data_source_id'), table_name='data_source_files')
    op.drop_table('data_source_files')
    # ### end Alembic commands ###
