"""add project scope to data sources and documents

Revision ID: fb3d7cd97083
Revises: 46f57811d4c3
Create Date: 2026-09-24 11:11:16.855785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3d7cd97083'
down_revision: Union[str, Sequence[str], None] = '46f57811d4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_data_sources_project_id'), 'data_sources', ['project_id'], unique=False)
    op.create_foreign_key(None, 'data_sources', 'projects', ['project_id'], ['id'])
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_column('documents', 'project_id')
    op.drop_constraint(None, 'data_sources', type_='foreignkey')
    op.drop_index(op.f('ix_data_sources_project_id'), table_name='data_sources')
    op.drop_column('data_sources', 'project_id')
    # ### end Alembic commands ###
